name: "Publish fragemwork coverage as diagnostics"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: ./.github/actions/fetch-codeql
      - name: Create empty database
        run: |
          DATABASE="${{ runner.temp }}/java-database"
          PROJECT="${{ runner.temp }}/java-project"
          codeql database init --language=java --source-root=$PROJECT/src/tmp/empty $DATABASE
          mkdir -p $PROJECT/src/tmp/empty
          touch $PROJECT/src/tmp/empty/Empty.java
          javac $PROJECT/src/main/java/Empty.java
          codeql database finalize $DATABASE --no-pre-finalize
      - uses: github/codeql-action/init@v1
        with:
          queries: "./java/ql/src/Diagnostics/CoverageDiagnostics.ql"
          languages: java
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
