name: Diff generated Models as Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "java/ql/src/utils/model-generator/**/*.*"

jobs:
  model-diff:
    runs-on: ubuntu-latest
    # environment:
    #   name: models
    #   url: https://github.com
    steps:
      - name: Clone self (github/codeql) for baseline
        uses: actions/checkout@v2
        with:
          path: codeql-baseline
          ref: ${{ github.base_ref }}
      - name: Clone self (github/codeql) with new generator
        uses: actions/checkout@v2
        with:
          path: codeql-head
          ref: ${{ github.ref }}
      - uses: ./codeql-baseline/.github/actions/fetch-codeql
      - name: Setup MaD comparison dbs
        run: |
          set -x
          mkdir lib-dbs
          downloadDatabase() {
            SLUG=$1
            SHORTNAME=${SLUG//[^a-zA-Z0-9_]/}
            projectId=`curl -s https://lgtm.com/api/v1.0/projects/g/$SLUG | jq .id`
            curl -L "https://lgtm.com/api/v1.0/snapshots/$projectId/java" -o $SHORTNAME.zip
            unzip -q -d $SHORTNAME-db $SHORTNAME.zip
            mkdir lib-dbs/$SHORTNAME/
            mv $SHORTNAME-db/`ls -1 $SHORTNAME-db`/* lib-dbs/$SHORTNAME/
          }

          downloadDatabase "apache/commons-codec"
          # downloadDatabase "apache/commons-io"
          downloadDatabase "apache/commons-beanutils"
          # downloadDatabase "apache/commons-lang"
          # downloadDatabase "apache/commons-validator"
          # downloadDatabase "apache/commons-csv"

          # TODO
          # spring-projects/spring-framework
          # guava
          # hibernate
          # aws
          # downloadDatabase "google/guava"
          # downloadDatabase "spring-projects/spring-framework"

          # downloadDatabase "FasterXML/jackson-core"
          # downloadDatabase "FasterXML/jackson-databind"
          # downloadDatabase "google/gson"
          # downloadDatabase "JodaOrg/joda-time"
          # downloadDatabase "apache/poi"
          # downloadDatabase "apache/commons-logging"
          # downloadDatabase "apache/commons-fileupload"
          

      - name: Generate MaD (Baseline)
        run: |
          set -x
          mkdir tmp-models
          MODELS=`pwd`/tmp-models
          MODE="baseline"
          DATABASES=`pwd`/lib-dbs

          analyzeDatabaseWithCheckout() {
            QL_VARIANT=$1
            DATABASE=$2
            cd codeql-$QL_VARIANT
            SHORTNAME=`basename $DATABASE`
            python java/ql/src/utils/model-generator/GenerateFlowModel.py $DATABASE $MODELS/${SHORTNAME}.qll
            mv $MODELS/${SHORTNAME}.qll $MODELS/${SHORTNAME}_${QL_VARIANT}.qll
            echo "$QL_VARIANT" >> $MODELS/${SHORTNAME}_${QL_VARIANT}.qll
            cd ..
          }
          
          for d in $DATABASES/*/ ; do
            ls -1 "$d"

            analyzeDatabaseWithCheckout "baseline" $d
            analyzeDatabaseWithCheckout "head" $d
          done          
      - name: Diff MaD
        run: |
          set -x
          npm install -g diff2html-cli
          MODELS=`pwd`/tmp-models
          ls -1 tmp-models/
          for m in $MODELS/*_baseline.qll ; do
            t="${m/baseline/"head"}"
            basename=`basename $m`
            name="diff_${basename/_baseline.qll/""}"
            (diff --color=always -w -u $m $t | diff2html -i stdin -F $MODELS/$name.html) || true
          done
      - uses: actions/upload-artifact@v2
        with:
          name: models
          path: tmp-models/*.qll
          retention-days: 5
      - uses: actions/upload-artifact@v2
        with:
          name: diffs
          path: tmp-models/*.html
          retention-days: 5
