name: Diff generated Models as Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "java/ql/src/utils/model-generator/**/*.*"

jobs:
  model-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Clone self (github/codeql) for baseline
        uses: actions/checkout@v2
        with:
          path: codeql-baseline
          ref: ${{ github.base_ref }}
      - name: Clone self (github/codeql) with new generator
        uses: actions/checkout@v2
        with:
          path: codeql-current
          ref: ${{ github.ref }}
      - name: Show setup
        run: |
          echo "Baseline: ${{ github.base_ref }}"
          echo "Current: ${{ github.ref }}"
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
      # - name: Download CodeQL CLI
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release download --repo "github/codeql-cli-binaries" --pattern "codeql-linux64.zip"
      # - name: Unzip CodeQL CLI
      #   run: unzip -q -d codeql-cli codeql-linux64.zip
      - uses: ./codeql-baseline/.github/actions/fetch-codeql
      - name: Setup MaD comparison dbs
        run: |
          mkdir tmp-models
      - name: Generate MaD (Baseline)
        run: |
          SLUG="apache/commons-codec"
          SHORTNAME="commonsCodec"
          MODE="baseline"  
          projectId=`curl -s https://lgtm.com/api/v1.0/projects/g/$SLUG | jq .id`
          curl -L "https://lgtm.com/api/v1.0/snapshots/$projectId/java" -o $SHORTNAME.zip
          unzip -q -d $SHORTNAME-db $SHORTNAME.zip
          DATABASE=`pwd`/$SHORTNAME-db/`ls -1 $SHORTNAME-db`
          cd codeql-$MODE
          python java/ql/src/utils/model-generator/GenerateFlowModel.py $DATABASE ../tmp-models/$SHORTNAME-$MODE.qll

          cp tmp-models/$SHORTNAME-$MODE.qll tmp-models/$SHORTNAME-OTHER.qll
          echo "foo" >> tmp-models/$SHORTNAME-OTHER.qll
          diff --color always -w -u tmp-models/$SHORTNAME-$MODE.qll tmp-models/$SHORTNAME-OTHER.qll