name: Diff generated Models as Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "java/ql/src/utils/model-generator/**/*.*"

jobs:
  model-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Clone self (github/codeql) for baseline
        uses: actions/checkout@v2
        with:
          path: codeql-baseline
          ref: ${{ github.base_ref }}
      - name: Clone self (github/codeql) with new generator
        uses: actions/checkout@v2
        with:
          path: codeql-current
          ref: ${{ github.ref }}
      - uses: ./codeql-baseline/.github/actions/fetch-codeql
      - name: Setup MaD comparison dbs
        run: |
          set -x
          mkdir lib-dbs
          downloadDatabase() {
            SLUG=$1
            SHORTNAME=$2
            projectId=`curl -s https://lgtm.com/api/v1.0/projects/g/$SLUG | jq .id`
            curl -L "https://lgtm.com/api/v1.0/snapshots/$projectId/java" -o $SHORTNAME.zip
            unzip -q -d $SHORTNAME-db $SHORTNAME.zip
            mkdir lib-dbs/$SHORTNAME-db/
            mv $SHORTNAME-db/`ls -1 $SHORTNAME-db`/* lib-dbs/$SHORTNAME-db/
          }

          downloadDatabase "apache/commons-codec" "commonsCodec"
      - name: Generate MaD (Baseline)
        run: |
          set -x
          mkdir tmp-models
          MODELS=`pwd`/tmp-models
          MODE="baseline"
          DATABASES=`pwd`/lib-dbs
          cd codeql-$MODE
          for d in $DATABASES/*/ ; do
            ls -1 "$DATABASES/$d"
            python java/ql/src/utils/model-generator/GenerateFlowModel.py $DATABASES/$d $MODELS/${d}_${MODE}.qll
            # remove 
            cp ../tmp-models/${d}_${MODE}.qll ../tmp-models/${d}_OTHER.qll
            echo "foo" >> ../tmp-models/${d}_OTHER.qll
          done          
      - uses: actions/upload-artifact@v2
        with:
          name: models
          path: tmp-models/
      - name: Diff MaD
        run: |
          set -x
          SHORTNAME="commonsCodec"
          MODE="baseline"
          ls -1 tmp-models/
          (diff --color=always -w -u tmp-models/${SHORTNAME}_${MODE}.qll tmp-models/${SHORTNAME}_OTHER.qll) || true